# see https://github.com/marketplace/stale

daysUntilStale: 60
daysUntilClose: 14
exemptLabels:
  - pinned
  - security
staleLabel: stale
markComment: >
  This issue has been automatically marked as stale because it has not had recent activity;
  will be closed if no further activity occurs within the next 14 days.
closeComment: >
  This issue has been automatically closed due to inactivity.
exemptProjects: true
exemptMilestones: true
exemptAssignees: true
only: issues
